-- Add high-impact operational events confirmed after the initial 2026/2027
-- impact event catalogue.

INSERT INTO impact_events (
  slug,
  name,
  starts_at,
  ends_at,
  local_date,
  year,
  category,
  impact_level,
  impact_scope,
  impact_type,
  country_code,
  location_code,
  timezone,
  description,
  business_impact_hint,
  is_holiday,
  status,
  source_name,
  source_url,
  metadata
) VALUES
(
  'beauty-fair-2026',
  'Beauty Fair 2026',
  '2026-09-05 10:00:00-03',
  '2026-09-08 20:00:00-03',
  '2026-09-05',
  2026,
  'commerce',
  'high',
  'municipality',
  'tourism_and_service_demand_spike',
  'BR',
  'SP-SAO-PAULO',
  'America/Sao_Paulo',
  'Feira profissional de beleza no Expo Center Norte, em São Paulo.',
  'Pode afetar hotelaria, mobilidade, alimentação, atendimento local, ativações de marca e demanda B2B do setor de beleza.',
  false,
  'scheduled',
  'Beauty Fair',
  'https://beautyfair.com.br/en/',
  '{"city":"São Paulo","state":"SP","venue":"Expo Center Norte","industry":"beauty","dates":["2026-09-05","2026-09-06","2026-09-07","2026-09-08"]}'::jsonb
),
(
  'nfl-rio-game-2026',
  'NFL Rio Game 2026',
  '2026-09-27 17:25:00-03',
  '2026-09-27 23:00:00-03',
  '2026-09-27',
  2026,
  'sports',
  'high',
  'municipality',
  'tourism_and_service_demand_spike',
  'BR',
  'RJ-RIO-DE-JANEIRO',
  'America/Sao_Paulo',
  'Jogo da temporada regular da NFL no Maracanã, no Rio de Janeiro.',
  'Pode afetar turismo, hotelaria, mobilidade, bares/restaurantes, segurança, atendimento local, mídia e demanda digital.',
  false,
  'scheduled',
  'Ticketmaster Brasil',
  'https://www.ticketmaster.com.br/event/nfl-2026-general-sale',
  '{"city":"Rio de Janeiro","state":"RJ","venue":"Maracanã","league":"NFL","teams":["Baltimore Ravens","Dallas Cowboys"]}'::jsonb
),
(
  'brasil-game-show-2026',
  'Brasil Game Show 2026',
  '2026-10-09 10:00:00-03',
  '2026-10-12 22:00:00-03',
  '2026-10-09',
  2026,
  'cultural',
  'high',
  'municipality',
  'tourism_and_service_demand_spike',
  'BR',
  'SP-SAO-PAULO',
  'America/Sao_Paulo',
  'Brasil Game Show 2026 no Distrito Anhembi, em São Paulo.',
  'Pode afetar mobilidade, hotelaria, alimentação, atendimento local, ativações de marca, varejo gamer e demanda digital.',
  false,
  'scheduled',
  'Distrito Anhembi',
  'https://distritoanhembi.com.br/events/brasil-game-show-bgs/',
  '{"city":"São Paulo","state":"SP","venue":"Distrito Anhembi","industry":"games","dates":["2026-10-09","2026-10-10","2026-10-11","2026-10-12"]}'::jsonb
),
(
  'sao-paulo-e-prix-2027',
  'São Paulo E-Prix 2027',
  '2027-03-13 08:00:00-03',
  '2027-03-13 20:00:00-03',
  '2027-03-13',
  2027,
  'sports',
  'high',
  'municipality',
  'traffic_disruption',
  'BR',
  'SP-SAO-PAULO',
  'America/Sao_Paulo',
  'Etapa brasileira do Campeonato Mundial de Fórmula E no Sambódromo do Anhembi.',
  'Pode afetar mobilidade, hotelaria, alimentação, transporte, atendimento local, mídia e demanda turística.',
  false,
  'scheduled',
  'Formula E',
  'https://www.fiaformulae.com/en/news/1074658/season-13-calendar-where-will-formula-e-be-racing-in-2026-27',
  '{"city":"São Paulo","state":"SP","venue":"Sambódromo do Anhembi","competition":"Formula E","season":"2026/27","round":6}'::jsonb
),
(
  'web-summit-rio-2027',
  'Web Summit Rio 2027',
  '2027-06-14 09:00:00-03',
  '2027-06-17 20:00:00-03',
  '2027-06-14',
  2027,
  'commerce',
  'high',
  'municipality',
  'tourism_and_service_demand_spike',
  'BR',
  'RJ-RIO-DE-JANEIRO',
  'America/Sao_Paulo',
  'Conferência internacional de tecnologia no Riocentro, no Rio de Janeiro.',
  'Pode afetar hotelaria, mobilidade, alimentação, eventos corporativos, atendimento local, startups, investidores, mídia e demanda B2B.',
  false,
  'scheduled',
  'Web Summit Rio',
  'https://rio.websummit.com/',
  '{"city":"Rio de Janeiro","state":"RJ","venue":"Riocentro","industry":"technology","dates":["2027-06-14","2027-06-15","2027-06-16","2027-06-17"]}'::jsonb
)
ON CONFLICT (slug, country_code) DO UPDATE SET
  name = EXCLUDED.name,
  starts_at = EXCLUDED.starts_at,
  ends_at = EXCLUDED.ends_at,
  local_date = EXCLUDED.local_date,
  year = EXCLUDED.year,
  category = EXCLUDED.category,
  impact_level = EXCLUDED.impact_level,
  impact_scope = EXCLUDED.impact_scope,
  impact_type = EXCLUDED.impact_type,
  location_code = EXCLUDED.location_code,
  timezone = EXCLUDED.timezone,
  description = EXCLUDED.description,
  business_impact_hint = EXCLUDED.business_impact_hint,
  is_holiday = EXCLUDED.is_holiday,
  status = EXCLUDED.status,
  source_name = EXCLUDED.source_name,
  source_url = EXCLUDED.source_url,
  metadata = EXCLUDED.metadata,
  updated_at = CURRENT_TIMESTAMP;
